import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <NavBar />
        <div>Hello World</div>
        <div>People do this</div>
      </body>
    </>
  );
};

export default Home;
